version: "3.9"
services:
  app:
    image: kmutt-oph
    container_name: kmutt-openhouse-app-dev
    ports:
      - "8080:3000"
    env_file:
      - .env
    environment:
      - NEXTAUTH_URL=http://localhost:8080
      - DATABASE_URL=mysql://root:testpassword@db:3306/kmutt-openhouse-act
      - NEXTAUTH_SECRET=testdevsrcret
      - EXTERNAL_JWT_SECRET=supersecrettest
    depends_on:
       - db

  db:
    image: mysql:8.0
    container_name: kmutt-oph-db-dev
    restart: always
    volumes:
     - ./mysql-data:/var/lib/mysql
    environment:
     MYSQL_ROOT_PASSWORD: testpassword
     MYSQL_DATABASE: kmutt-open-house-act
    expose:
     - "3306"
    ports:
     - "3307:3306"

  PMA:
    depends_on:
     - db
    image: phpmyadmin/phpmyadmin
    container_name: kmutt-oph-pma-dev
    restart: always
    ports:
     - "8090:80"
    environment:
      PMA_HOST: db
