version: "3.9"
services:
  openhouse_app_ex:
    image: kmutt_oph_prod
    container_name: kmutt-openhouse-app-prod_ex
    ports:
      - "80:80"
    env_file:
      - .env
    environment:
      - NEXTAUTH_URL=${NEXTAUTH_URL}
      - DATABASE_URL=${DATABASE_URL}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - EXTERNAL_JWT_SECRET=${EXTERNAL_JWT_SECRET}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASS=${SMTP_PASS}
      - NEXT_PUBLIC_BASE_URL=${NEXT_PUBLIC_BASE_URL}
    mem_limit: 3g
    cpus: 1.0
