version: "3.9"

services:
  # Nginx reverse proxy + sticky session
  nginx:
    image: nginx:latest
    container_name: openhouse_nginx
    ports:
      - "80:80"
      - "8080:8080"  # metrics
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx_logs:/var/log/nginx
    depends_on:
      - openhouse_app_ex
      - openhouse_app_ex_2
      - openhouse_app_ex_3

  # Next.js containers
  openhouse_app_ex:
    image: kmutt_oph_prod
    container_name: kmutt-openhouse-app-prod_1
    ports:
      - "81:80"
    env_file:
      - .env
    environment:
      - NEXTAUTH_URL=${NEXTAUTH_URL}
      - DATABASE_URL=${DATABASE_URL}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - EXTERNAL_JWT_SECRET=${EXTERNAL_JWT_SECRET}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASS=${SMTP_PASS}
      - NEXT_PUBLIC_BASE_URL=${NEXT_PUBLIC_BASE_URL}
      - NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
      - NEXT_PUBLIC_SUPABASE_SERVICE_ROLE_KEY=${NEXT_PUBLIC_SUPABASE_SERVICE_ROLE_KEY}
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}

  #  mem_limit: 1.5g
  #  cpus: 1.0

  openhouse_app_ex_2:
    image: kmutt_oph_prod
    container_name: kmutt-openhouse-app-prod_2
    ports:
      - "82:80"
    env_file:
      - .env
    environment:
      - NEXTAUTH_URL=${NEXTAUTH_URL}
      - DATABASE_URL=${DATABASE_URL}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - EXTERNAL_JWT_SECRET=${EXTERNAL_JWT_SECRET}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASS=${SMTP_PASS}
      - NEXT_PUBLIC_BASE_URL=${NEXT_PUBLIC_BASE_URL}
      - NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
      - NEXT_PUBLIC_SUPABASE_SERVICE_ROLE_KEY=${NEXT_PUBLIC_SUPABASE_SERVICE_ROLE_KEY}
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
 #   mem_limit: 1.5g
 #   cpus: 1.0

  openhouse_app_ex_3:
    image: kmutt_oph_prod
    container_name: kmutt-openhouse-app-prod_3
    ports:
      - "83:80"
    env_file:
      - .env
    environment:
      - NEXTAUTH_URL=${NEXTAUTH_URL}
      - DATABASE_URL=${DATABASE_URL}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - EXTERNAL_JWT_SECRET=${EXTERNAL_JWT_SECRET}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASS=${SMTP_PASS}
      - NEXT_PUBLIC_BASE_URL=${NEXT_PUBLIC_BASE_URL}
      - NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
      - NEXT_PUBLIC_SUPABASE_SERVICE_ROLE_KEY=${NEXT_PUBLIC_SUPABASE_SERVICE_ROLE_KEY}
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
#    mem_limit: 1.5g
#    cpus: 1.0

  # Node exporter สำหรับ CPU/RAM metrics (รองรับ cgroup v2)
  node-exporter:
    image: prom/node-exporter:latest
    container_name: node_exporter
    network_mode: host
    pid: "host"
    restart: unless-stopped

  # Prometheus
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro

  # Grafana
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
